// src/app/api/subscribe/route.ts
import { NextRequest, NextResponse } from 'next/server';
import { Client } from '@notionhq/client';

const NOTION_TOKEN = process.env.NOTION_TOKEN;
const NEWSLETTER_DB_ID = 'c03fb9bae12443e9a620859d8a4db2c1';

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { name, email, interests } = body;

    // Validation
    if (!name || !email) {
      return NextResponse.json(
        { success: false, error: 'Name and email are required' },
        { status: 400 }
      );
    }

    // Email validation
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(email)) {
      return NextResponse.json(
        { success: false, error: 'Invalid email format' },
        { status: 400 }
      );
    }

    if (!NOTION_TOKEN) {
      console.error('NOTION_TOKEN is not configured');
      return NextResponse.json(
        { success: false, error: 'Server configuration error' },
        { status: 500 }
      );
    }

    const notion = new Client({ auth: NOTION_TOKEN });

    // Map interests to Notion multi-select format
    const interestOptions = (interests || []).map((interest: string) => ({
      name: interest
    }));

    // Create page in Notion database
    await notion.pages.create({
      parent: { database_id: NEWSLETTER_DB_ID },
      properties: {
        Name: {
          title: [
            {
              text: {
                content: name
              }
            }
          ]
        },
        Email: {
          email: email
        },
        Interests: {
          multi_select: interestOptions
        }
        // Date is auto-generated by Notion (Created Time property)
      }
    });

    return NextResponse.json({ 
      success: true, 
      message: 'Successfully subscribed to newsletter' 
    });

  } catch (error) {
    console.error('Newsletter subscription error:', error);
    return NextResponse.json(
      { success: false, error: 'Failed to subscribe. Please try again.' },
      { status: 500 }
    );
  }
}
