"use client"
import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const translations = {
  en: {
    // Header
    'header.title': 'InnovateXP Limited',
    'header.subtitle': 'Innovate • Transform • Experience',
    'quick.product': 'Quick Product/Service Overview',
    // Hero Section
    'hero.title': 'You have 40 WhatsApp messages. Which one do you reply to first?',
    'hero.tagline': '',
    'hero.description':
      'InnovateXP builds AI systems that help Hong Kong SMEs stop losing deals to slow replies, missed follow-ups, and scattered spreadsheets.',
    'hero.cta': 'Contact Us',
    'hero.book_meeting': 'Book a Free 30-min Consultation',
    'hero.tagline_en': '',
    'hero.image_alt': 'Larry Lo presenting — InnovateXP founder, AI & CRM for Hong Kong SMEs',
    'hero.explore_services': 'Explore Our Products',
    'why.title': 'Why InnovateXP',
    'why.1.label': '14+ years in tech',
    'why.1.sub': 'Hands-on systems and consulting, not slide decks only.',
    'why.2.label': '2,000+ participants',
    'why.2.sub': 'Event and CRM systems proven at real scale.',
    'why.3.label': 'HKSTP incubation alumni',
    'why.3.sub': 'Hong Kong startup ecosystem roots.',
    'why.4.label': 'Local AI + CRM team',
    'why.4.sub': 'Cantonese / English delivery for regional SMEs.',
    'product.entry.section_label': 'What are you trying to solve?',
    'product.entry.eventxp.title':
      '🎟️ I run events and lose track of attendees after the day',
    'product.entry.eventxp.blurb': 'See how check-ins become ranked follow-up lists.',
    'product.entry.eventxp.cta': '→ See EventXP',
    'product.entry.smartsales.title':
      '💬 My WhatsApp inbox is full of leads I never followed up on',
    'product.entry.smartsales.blurb': 'See triage, AI drafts, and human-approved sending.',
    'product.entry.smartsales.cta': '→ See SmartSales CRM',
    'product.entry.ai.title': '🤖 I want AI in my business but don\'t know where to start',
    'product.entry.ai.blurb': 'Start with one workflow, prove ROI in 30 days, then expand.',
    'product.entry.ai.cta': '→ See AI Consulting',
    'eventxp.headline': 'You spent HKD 50,000 on an event. What happened to those 200 contacts?',
    'smartsales.headline': 'Your best salesperson follows up within 2 hours. Does yours?',
    'mockup.checkin':
      '🎬 Watch EventXP in a live 15-min walkthrough. We\'ll show you a real post-event report from a recent BNI chapter event. → Book Demo: info@innovatexp.com',
    'mockup.checkin.alt': 'EventXP admin — check-in and dashboard screenshot',
    'mockup.pipeline':
      '🎬 See a live SmartSales inbox walkthrough — 15 minutes. We\'ll show you how a real lead gets triaged, drafted, and followed up. → Book Demo: info@innovatexp.com',
    'mockup.ai': 'AI drafting & workflow (mockup)',
    'contact.form.hint.name': 'How we should address you or your team.',
    'contact.form.hint.email': 'We reply within 1–2 business days.',
    'contact.form.hint.message': 'Briefly describe your biggest AI / CRM or event challenge right now.',
    'footer.book_cta': 'Book a strategy call',
    'mobile.cta_contact': 'Contact',
    'roi.show_more': 'Show deeper ROI scenarios',
    'roi.show_less': 'Show less',
    'aiconsulting.who.more': 'See who this is for (expand)',
    
    // Bookme Page
    'bookme.title': '📅 Book Business Consultation',
    'bookme.subtitle': 'One-on-One Business Consultation — times exclude everything on your Notion calendar (bookings + busy blocks)',
    'bookme.header.title': 'InnovateXP Limited',
    'bookme.header.subtitle': 'Book Business Consultation',
    'bookme.header.back': '← Back to Home',
    'bookme.success.title': 'Your business consultation booking has been successful! Added to Notion calendar.',
    'bookme.success.subtitle': 'Your business consultation booking was not successful! Please contact InnovateXP Limited ASAP: info@innovatexp.com',
    'bookme.whatsapp.title': '📱 Send WhatsApp Confirmation Message',
    'bookme.whatsapp.message': 'Your booking has been successfully added to Notion calendar! Click the button below to send confirmation message to WhatsApp.',
    'bookme.whatsapp.button': 'Open WhatsApp to Send',
    'bookme.whatsapp.later': 'Later',
    'bookme.error.title': 'Please fill in all required fields and select date and time.',
    'bookme.error.email': 'Please enter a valid email address.',
    'bookme.error.slots': 'Unable to fetch available time slots',
    'bookme.error.fetch': 'Failed to fetch time slots',
    'bookme.error.booking': 'Booking failed, please try again later.',
    'bookme.error.general': 'Booking failed',
    'bookme.info.title': '📋 Booking Information',
    'bookme.info.monday_friday': '• Booking time is Monday to Friday, 9:00 AM to 5:00 PM',
    'bookme.info.one_hour': '• Each session is 1 hour of one-on-one consultation',
    'bookme.info.confirmation': '• After successful booking, you will receive confirmation email and calendar invitation',
    'bookme.info.cancel': '• For cancellation or changes, please notify 24 hours in advance',
    'bookme.info.online': '• Consultation can choose online meeting or in-person visit',
    'bookme.info.notion': '• Available slots sync with Notion: any event with a date on that day blocks those hours (use start + end time for blocks like 2–5 pm; optional NOTION_BUSY_DB_ID for a second calendar)',
    'bookme.date.label': '📅 Select Date',
    'bookme.date.required': '* Not available on weekends (Saturday and Sunday)',
    'bookme.time.label': '⏰ Select Time (1 hour)',
    'bookme.time.select': 'Please select a date first',
    'bookme.time.loading': 'Loading...',
    'bookme.time.no_slots': 'No available time slots for this date.<br />Please select another date.',
    'bookme.time.hour': '* Each session is 1 hour of one-on-one consultation',
    'bookme.selected.title': 'Selected:',
    'bookme.visitor.title': '👤 Visitor Information',
    'bookme.visitor.name': 'Your Name',
    'bookme.visitor.email': 'Email',
    'bookme.visitor.phone': 'Contact Phone',
    'bookme.visitor.company': 'Company Name',
    'bookme.visitor.message': 'Consultation Content / Message',
    'bookme.visitor.placeholder.name': 'Please enter your name',
    'bookme.visitor.placeholder.email': 'your@email.com',
    'bookme.visitor.placeholder.phone': '+852 1234 5678',
    'bookme.visitor.placeholder.company': 'Your company name',
    'bookme.visitor.placeholder.message': 'Please briefly describe what you want to consult about, such as: AI integration solutions, system development needs, corporate training, etc...',
    'bookme.submit.processing': 'Processing...',
    'bookme.submit.confirm': 'Confirm Booking',
    'bookme.modal.success.title': 'Booking Successful',
    'bookme.modal.error.title': 'Booking Failed',

    // Vision Section
    'vision.title': 'Our Vision',
    'vision.brand': 'InnovateXP Limited',
    'vision.tagline': 'Innovate • Transform • Experience',
    'vision.description':
      'Most SMEs are stuck in the Red Ocean — competing on price, doing what everyone else does, and watching margins shrink. InnovateXP builds the systems that let you escape it. Not by automating everything at once, but by finding the one workflow where AI creates an unfair advantage for your business — and building that first. That\'s the Desert Oasis approach. Your competitors are busy in the crowd. You build where they can\'t follow.',
    'vision.innovate': 'Innovate',
    'vision.innovate_desc': 'Challenge the status quo with AI-powered solutions that turn data into your strategic asset.',
    'vision.transform': 'Transform',
    'vision.transform_desc': 'Evolve your business operations from manual processes to intelligent automation.',
    'vision.experience': 'Experience',
    'vision.experience_desc': 'Deliver exceptional results that exceed expectations and create lasting impact.',

    // Core Services Section (Three Main Services)
    'services.title': 'Our Core Services',
    'services.ai_crm.title': 'SmartSales CRM',
    'services.ai_crm.subtitle': 'Intelligent Customer Management System',
    'services.ai_crm.benefit1': 'Lightning-fast responses with AI Smart Draft',
    'services.ai_crm.benefit2': 'Automated booking handling',
    'services.ai_crm.benefit3': 'Eliminate missed orders with auto-tagging',
    'services.ai_crm.cta': 'Learn About AI CRM Solution',
    'services.checkin.title': 'Check-in System',
    'services.checkin.subtitle': 'EventXP',
    'services.checkin.benefit1': 'Real-time attendee list',
    'services.checkin.benefit2': 'QR code scanning',
    'services.checkin.benefit3': 'Automated statistics',
    'services.checkin.cta': 'Learn About Check-in System',
    'services.courses.title': 'AI Consulting Services',
    'services.courses.subtitle': 'Help Enterprises Deploy AI from 0 to 1',
    'services.courses.benefit1': 'Implementation Assessment: Significantly reduce trial-and-error costs',
    'services.courses.benefit2': 'Customized AI Agent & Architecture Design',
    'services.courses.benefit3': 'Hands-on Prompt Engineering Training',
    'services.courses.cta': 'Learn About Consulting Services',
    
    // About Section - REVISED: Technical Authority & Corrected Facts
    'about.title': 'About Us',
    'about.intro.title': 'About InnovateXP Limited',
    'about.intro.p1': "Founded by Larry Lo, former Organizer of Google Developer Group Hong Kong (until 2025) and HKSTP Incubation alumnus (2017-2019). We are not just consultants; we are hands-on system architects.",
    'about.intro.p2': 'Our Philosophy: "Connecting Technology through Passion, Perfection, and Premier standards." We leverage years of experience in System Design and Real-world Development to help you build your "Desert Oasis".',
    'about.intro.p3': 'We combine the agility of modern tech stacks with the stability required for enterprise operations, delivering practical, actionable AI solutions.',
    
    'about.tags.title': 'Our Strategy & Capability',
    'about.tags.red_ocean.title': 'Red Ocean Dilemma',
    'about.tags.red_ocean.description': 'High competition, low margins. Doing what everyone else does only dilutes your value. You need a technological edge to escape.',
    'about.tags.desert_oasis.title': 'Desert Oasis Strategy',
    'about.tags.desert_oasis.description': 'Use AI to build a data moat. Create unique value that competitors cannot easily copy, establishing your own blue ocean.',
    'about.tags.community.title': 'Proven Technical Capability',
    'about.tags.community.description': 'Founder Larry Lo brings proven experience in architecting systems that handle 2,000+ active participants. We focus on robust execution over empty talk.',
    
    'about.story.title': 'Mission & 2026 Roadmap',
    'about.story.content': 'InnovateXP empowers organizations to upgrade their business through AI and strategic system blueprints. 2026 Roadmap: Jan (Now) - EventXP Launch; Feb - SmartSales CRM; Mar - AI Playbook; Apr - SME Masterclass. We are committed to practical implementation.',

    // Partnership Section
    'partnership.title': 'Trusted Partners & Affiliations',
    'partnership.subtitle': 'Building Innovation Through Strategic Partnerships',
    'partnership.agilizing.title': 'Agilizing Education Center',
    'partnership.agilizing.desc': 'Agile & business training partner',
    'partnership.bni_anchor.title': 'BNI Anchor',
    'partnership.bni_anchor.desc': 'Referral network & leadership',
    'partnership.linkedinlocal.title': 'LinkedInLocal Asia',
    'partnership.linkedinlocal.desc': 'APAC professional meetups',
    'partnership.ex_io.title': 'EX.IO',
    'partnership.ex_io.desc': 'Digital asset & exchange ecosystem partner',
    'partnership.kirapay.title': 'KiraPay',
    'partnership.kirapay.desc': 'Payments & fintech collaboration',
    
    // Contact Section
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Please leave a message, we will get back to you as soon as possible.',
    'contact.form.name': 'Name',
    'contact.form.email': 'Email Address',
    'contact.form.content': 'Content',
    'contact.form.placeholder': 'Please fill in',
    'contact.form.submit': 'Send Email',
    'contact.form.success': 'Email Sent',
    
    // Story Section (3-Step)
    'story.title': 'Our Strategy',
    'story.step1.title': 'Red Ocean Dilemma',
    'story.step1.description': 'High competition, low margins, everyone doing the same thing',
    'story.step2.title': 'Desert Oasis',
    'story.step2.description': 'Create unique value with AI to escape competition',
    'story.step3.title': 'Cola Theory',
    'story.step3.description': 'Same product, different value based on context and environment',
    
    // Ideal Client Section
    'ideal.title': 'Ideal Referral / Ideal Client Profile',
    'ideal.subtitle': 'Problems We Solve for SMEs',
    'ideal.problem1': 'Too many WhatsApp queries',
    'ideal.problem2': 'Missed orders',
    'ideal.problem3': 'Excel chaos',
    'ideal.problem4': 'Lack of CRM automation',
    'ideal.value': 'Clear value proposition for SMEs',
    
    // Founder Section
    'founder.title': 'Founder & Credentials',
    'founder.name': 'Larry Lo',
    'founder.credential1': 'SAFe Certified',
    'founder.credential2': 'Google Developer Group Speaker',
    'founder.credential3': '200+ Developer Training Experience',
    'founder.credential4': 'HKSTP Incubation',
    'founder.credential5': 'JCI/BNI Leadership',
    
    // Achievements Section
    'achievements.title': 'Track Record & Impact',
    'achievements.kmb':
      'KMB & Government Projects',
    'achievements.government':
      'Delivered production systems operating in real-time, high-availability environments — the same engineering discipline we bring to every SME build.',
    'achievements.sme': 'SME Projects',
    'achievements.engagement':
      'Doubled active user engagement within 3 months of launch (SME client, 2025)',
    'achievements.case': 'AI × CRM success story',
    
    // Credibility Badges
    'credibility.title': 'Partners & Recognition',
    'credibility.gdg': 'GDG Hong Kong',
    'credibility.hku': 'HKU',
    'credibility.hkstp': 'HKSTP',
    'credibility.jci': 'JCI',
    'credibility.bni': 'BNI',
    
    // Product Showcases
    'showcase.title': '',
    'showcase.problem_label': 'Problem:',
    'showcase.solution_label': 'Solution:',
    'showcase.features_label': 'Key Features:',
    'showcase.screenshot_coming': '📬 Book a 15-min live walkthrough — info@innovatexp.com',
    'showcase.checkin.title': 'EventXP',
    'showcase.checkin.subtitle': 'QR Code + Real-time Sync',
    'showcase.checkin.problem': 'Manual check-in prone to errors and missing data, time-consuming post-event statistics',
    'showcase.checkin.solution': 'QR Code scanning check-in, instantly syncs to database, chapter leaders can view attendance rates and reports anytime',
    'showcase.checkin.features': 'QR Code fast check-in; Auto statistics reports; Live participant list; Multi-event support',
    'showcase.checkin.cta': 'Book Demo for Check-in System',
    'showcase.booking.title': 'Booking / Reservation System',
    'showcase.booking.subtitle': 'Notion Calendar + Email + WhatsApp Notifications',
    'showcase.booking.problem': 'Back-and-forth WhatsApp time confirmations, scattered calendars, easy to double-book or miss appointments',
    'showcase.booking.solution': 'Clients self-select time slots, system auto-checks availability, instantly adds to Notion Calendar upon confirmation with .ics calendar attachment and WhatsApp confirmation',
    'showcase.booking.features': 'Visual calendar selection; Real-time availability check; Notion Calendar sync; Auto-send .ics email attachment',
    'showcase.booking.cta': 'Book Demo for Booking System',
    'showcase.ai_crm.title': 'AI × CRM',
    'showcase.ai_crm.subtitle': 'Intelligent Customer Relationship Management System',
    'showcase.ai_crm.problem': 'WhatsApp messages scattered everywhere, manual recording prone to errors, no systematic way to track customer status and sales progress',
    'showcase.ai_crm.solution': 'Integrated AI for auto-tagging, draft replies, follow-up reminders, centralized customer information management with sales funnel at a glance',
    'showcase.ai_crm.feature1': 'AI Smart Draft - Quickly generate professional replies',
    'showcase.ai_crm.feature2': 'Auto-tagging - Automatic customer status categorization',
    'showcase.ai_crm.feature3': 'Follow-up reminders - Eliminate missed orders',
    'showcase.ai_crm.feature4': 'Sales funnel - Visualize customer journey management',
    'showcase.ai_crm.cta': 'Book Demo for AI CRM',
    'ideal.cta': 'Book Consultation Now',
    
    // Pricing Section
    'pricing.title': 'Pricing Packages',
    'pricing.subtitle': 'Data Monetization + Community Retention = Long-term Growth',
    'pricing.promotion': 'Q1 Launch Special',
    'pricing.promotion_detail': 'Sign up for 1 year, get 1 Man-day Custom Consultation FREE',
    
    // EventXP Product
    'pricing.insight.name': 'EventXP',
    'pricing.insight.tagline': 'Turn Event Data into Revenue Growth',
    'pricing.insight.subtitle':
      'You spent HKD 50,000 on an event. What happened to those 200 contacts?',
    'pricing.insight.description':
      'EventXP turns every check-in into a ranked lead list — automatically. Know who to follow up with, and when, before your competitors do.',
    'pricing.insight.value':
      'The AI Growth plan costs HKD $400/month more than Professional. A single recovered client from a smarter follow-up list typically pays for a year\'s subscription. The math is straightforward.',
    
    'pricing.insight.tier1.name': 'Starter',
    'pricing.insight.tier1.price': 'HKD $1,480',
    'pricing.insight.tier1.period': '/ month',
    'pricing.insight.tier1.target': '1 community · Min. 6 months',
    'pricing.insight.tier1.feature1': 'Unlimited event creation & QR Code check-in',
    'pricing.insight.tier1.feature2': 'Smart Conversion List & Retention Strategy Engine',
    'pricing.insight.tier1.feature3': 'Ops support & backups · 2 onsite events included',
    'pricing.insight.tier1.feature4': '3 months warranty · 1 product review meeting',
    
    'pricing.insight.tier2.name': 'Growth',
    'pricing.insight.tier2.price': 'HKD $1,980',
    'pricing.insight.tier2.period': '/ month',
    'pricing.insight.tier2.subtitle': '(Only +$500 more than Starter)',
    'pricing.insight.tier2.badge': 'Best Value',
    'pricing.insight.tier2.target': '2 communities · Min. 12 months',
    'pricing.insight.tier2.feature1': 'All Starter features, PLUS:',
    'pricing.insight.tier2.feature2': '🕵️ Lead scoring insight (check-in timing + attendance + engagement)',
    'pricing.insight.tier2.feature3': '3 onsite events · 2 Strategic AI Consultancy sessions/year',
    'pricing.insight.tier2.feature4': '1 year warranty · 2 product review meetings',
    'pricing.insight.tier2.note': '💡 Ideal for community retention and data-driven follow-up. Prepay 1 year: 10% off; 2 years: 20% off.',
    
    'pricing.insight.tier3.name': 'Enterprise',
    'pricing.insight.tier3.price': 'HKD $2,480',
    'pricing.insight.tier3.period': '/ month',
    'pricing.insight.tier3.target': '4 communities · Min. 12 months',
    'pricing.insight.tier3.feature1': 'All Growth features, PLUS 1 AI Consultancy session (60 min) every month',
    'pricing.insight.tier3.feature2': '4 onsite events · 2 years warranty · 3 product review meetings',
    'pricing.insight.tier3.feature3': 'Continuous optimization, workflow automation & strategy support',
    
    'pricing.insight.setup':
      'If we confirm the booking person is a BNI member, the scenario and pricing may be negotiable. For details, ',
    'pricing.insight.setup_cta': 'book a consultation',
    'eventxp.communities_support':
      'Event support by plan: Starter — 1 community; Growth — 2 communities; Enterprise — 4 communities. Includes one trial event.',
    'mockup.pipeline_kanban':
      '🎬 Live walkthrough: pipeline / Kanban — Book: info@innovatexp.com',
    'mockup.pipeline_inbox':
      '🎬 Live walkthrough: inbox triage & drafts — Book: info@innovatexp.com',
    
    // SmartSales CRM Product
    'pricing.crm.name': 'SmartSales CRM',
    'pricing.crm.tagline': 'Your best salesperson follows up within 2 hours. Does yours?',
    'pricing.crm.subtitle': 'WhatsApp-first revenue recovery for Hong Kong teams',
    'pricing.crm.description':
      'SmartSales CRM watches your WhatsApp inbox, ranks every lead by urgency, and drafts a reply in Cantonese or English. You review, tweak 20%, and send. No bot feel. No missed deals.',
    'pricing.crm.value':
      'Our users typically reclaim 3+ hours per week previously spent on manual WhatsApp tracking and copy-pasting replies. (Based on onboarded SME clients, March 2026)',
    
    'pricing.crm.feature1.title': 'AI Reply Drafts — Cantonese & English',
    'pricing.crm.feature1.desc':
      'When a lead says \'too expensive\', SmartSales drafts a value-focused reply in your brand\'s voice. You edit it, you send it. The customer never knows AI was involved — because it wasn\'t. You were.',
    'pricing.crm.feature2.title': 'Intelligent Scheduling',
    'pricing.crm.feature2.desc': 'Auto-booking: Integrates with Google/Outlook Calendar, AI bot confirms availability in chat and sends meeting invites.',
    'pricing.crm.feature3.title': 'Insight Reporting',
    'pricing.crm.feature3.desc': 'Sales forecasting: AI analyzes current pipeline and predicts monthly revenue achievement rate.',
    
    'pricing.crm.tier1.name': 'Starter',
    'pricing.crm.tier1.price': 'HKD $2,800',
    'pricing.crm.tier1.period': '/ month',
    'pricing.crm.tier1.target': 'Lightweight version',
    'pricing.crm.tier1.feature1': 'Basic CRM functions (Customer database)',
    'pricing.crm.tier1.feature2': 'Basic AI writing (Email draft)',
    'pricing.crm.tier1.feature3': 'Standard sales reports',
    
    'pricing.crm.tier2.name': 'Pro',
    'pricing.crm.tier2.price': 'HKD $4,800',
    'pricing.crm.tier2.period': '/ month',
    'pricing.crm.tier2.badge': 'Full AI Power',
    'pricing.crm.tier2.target': 'Full AI features',
    'pricing.crm.tier2.feature1': 'Advanced AI: Auto-reply suggestions, smart scheduling, churn alerts',
    'pricing.crm.tier2.feature2': 'Insight Reports: AI sales forecasting & strategic recommendations',
    'pricing.crm.tier2.feature3': 'WhatsApp / Email dual integration',
    
    'pricing.crm.tier3.name': 'Onboarding & Setup',
    'pricing.crm.tier3.price': 'From HKD $15,000',
    'pricing.crm.tier3.period': '(one-time)',
    'pricing.crm.tier3.target': '',
    'pricing.crm.tier3.feature1': 'Migration from your existing spreadsheet or CRM',
    'pricing.crm.tier3.feature2': 'Custom AI prompt training in your product\'s brand voice',
    'pricing.crm.tier3.feature3': '2-hour team walkthrough session',
    'pricing.crm.tier3.feature4':
      'Most clients go live within 5–7 business days. Not sure if you need this? Book a free 30-min chat first.',
    
    'pricing.cta': 'Book Consultation',
    'pricing.contact': 'Contact for Details',
    
    // Roadmap Section
    'roadmap.title': '2026 Roadmap',
    'roadmap.jan': 'January - Check-in System Launch',
    'roadmap.feb': 'February - AI Customer Management System',
    'roadmap.mar': 'March - AI Practical Handbook',
    'roadmap.apr': 'April - SME AI Practical Course',
    
    // Newsletter Section
    'newsletter.title': 'Stay Updated',
    'newsletter.subtitle': 'Subscribe to our newsletter for the latest AI insights and updates',
    'newsletter.name': 'Your Name',
    'newsletter.email': 'Your Email',
    'newsletter.interests': 'Interests',
    'newsletter.interest.ai': 'AI',
    'newsletter.interest.tech': 'Tech',
    'newsletter.interest.crm': 'CRM',
    'newsletter.interest.events': 'Events',
    'newsletter.subscribe': 'Subscribe',
    'newsletter.success': 'Successfully subscribed! Thank you for joining us.',
    'newsletter.error': 'Subscription failed. Please try again.',
    
    // AI Consulting Section
    'ai_consulting.title': 'Every AI project that fails does so in the first 3 weeks. Here\'s why.',
    'ai_consulting.subtitle':
      'Most SMEs pick the wrong tool, scope too broadly, and lose momentum before seeing results. InnovateXP\'s consulting starts with one workflow, proves ROI in 30 days, then expands — controlled risk, measurable outcomes.',
    'ai_consulting.description': '',
    'ai_consulting.package1.name': 'AI Readiness Audit',
    'ai_consulting.package1.price': 'Starting from HKD $8,000',
    'ai_consulting.package1.desc': 'Comprehensive assessment of your organization\'s AI readiness and opportunities',
    'ai_consulting.package1.feature1': 'Current state analysis',
    'ai_consulting.package1.feature2': 'AI opportunity identification',
    'ai_consulting.package1.feature3': 'Implementation roadmap',
    'ai_consulting.package2.name': 'Custom Agent Build',
    'ai_consulting.package2.price': 'Starting from HKD $25,000',
    'ai_consulting.package2.desc': 'Tailored AI agents designed for your specific business needs',
    'ai_consulting.package2.feature1': 'Custom workflow design',
    'ai_consulting.package2.feature2': 'Integration with existing systems',
    'ai_consulting.package2.feature3': 'Ongoing support & optimization',
    'ai_consulting.package3.name': 'Prompt Training Bootcamp',
    'ai_consulting.package3.price': 'Starting from HKD $12,000',
    'ai_consulting.package3.desc': 'Hands-on training for your team to master AI prompting',
    'ai_consulting.package3.feature1': 'Interactive workshops',
    'ai_consulting.package3.feature2': 'Real-world case studies',
    'ai_consulting.package3.feature3': 'Custom prompt library',
    
    // Navigation (anchors align to page sections)
    'nav.home': 'Home',
    'nav.eventxp': 'EventXP',
    'nav.smartsales': 'SmartSales CRM',
    'nav.ai_consulting': 'AI consulting',
    'nav.about': 'About us',
    'nav.contact': 'Contact',
    'nav.vision': 'Vision',
    'nav.partnership': 'Partnership',
    
    // Footer
    'footer.copyright': `© ${new Date().getFullYear()} InnovateXP Limited. All rights reserved.`,
    
    // FAQ Sections
    'faq.smartsales.title': 'SmartSales CRM - Frequently Asked Questions',
    'faq.smartsales.q1': 'What is AI CRM and how does it differ from traditional CRM?',
    'faq.smartsales.a1': 'AI CRM is customer relationship management software enhanced with artificial intelligence. Unlike traditional CRM that only stores data, AI CRM automatically drafts follow-up messages, predicts which leads will convert, and prioritizes prospects based on behavior patterns. It saves SMEs 3+ hours daily on repetitive sales tasks.',
    'faq.smartsales.q2': 'Can AI CRM integrate with WhatsApp for Hong Kong businesses?',
    'faq.smartsales.a2': 'Yes. SmartSales CRM integrates directly with WhatsApp Business API, allowing Hong Kong businesses to receive inquiries, auto-draft responses in Cantonese or English, and track conversation history—all within one dashboard. Human approval is required before sending.',
    'faq.smartsales.q3': 'How much does AI CRM cost in Hong Kong?',
    'faq.smartsales.a3': 'SmartSales CRM starts from HKD 2,800/month for the Starter plan and HKD 4,800/month for the Pro plan with full AI features. Enterprise pricing depends on user count and integration requirements. Contact us for a custom quote.',
    'faq.smartsales.q4': 'How long does it take to implement AI CRM?',
    'faq.smartsales.a4': 'Basic setup takes 1-2 weeks including data migration and team training. Full WhatsApp integration and custom workflows typically require 3-4 weeks. We provide hands-on onboarding support throughout.',
    'faq.smartsales.q5': 'What ROI can I expect from AI-powered customer management?',
    'faq.smartsales.a5':
      'Our onboarded SME clients (through March 2026) typically reclaim 3+ hours per week previously spent on manual WhatsApp tracking and copy-pasting replies; timelines vary by team size and workflow.',
    
    'faq.eventxp.title': 'EventXP - Frequently Asked Questions',
    'faq.eventxp.q1': 'What is EventXP event check-in system?',
    'faq.eventxp.a1': 'EventXP is an event intelligence platform that transforms check-ins into business insights. Beyond attendance tracking, it predicts which attendees are most likely to buy, renew memberships, or require follow-up—turning event data into actionable sales leads.',
    'faq.eventxp.q2': 'How does QR code check-in work for events?',
    'faq.eventxp.a2': 'Guests receive a unique QR code via email or WhatsApp. At the event, staff scan the code using EventXP\'s mobile app. The system instantly logs attendance, matches the guest profile to your CRM, and can trigger automated follow-ups post-event.',
    'faq.eventxp.q3': 'Can EventXP handle multiple simultaneous events?',
    'faq.eventxp.a3': 'Yes. EventXP supports unlimited concurrent events with separate dashboards, real-time attendance tracking, and consolidated reporting across all events.',
    'faq.eventxp.q4': 'What is the cost of EventXP event management system?',
    'faq.eventxp.a4': 'EventXP Starter is HKD 1,480/month (1 community, 2 onsite events). Growth is HKD 1,980/month with AI Potential Interest Insight and 2 AI consultancy sessions/year. Enterprise is HKD 2,480/month with monthly AI consultancy and 4 onsite events. One-off setup: BNI members may receive negotiable pricing — book a call for details.',
    
    'faq.aiconsulting.title': 'AI Consulting - Frequently Asked Questions',
    'faq.aiconsulting.q1': 'What is prompt engineering training?',
    'faq.aiconsulting.a1': 'Prompt engineering training teaches your team how to effectively communicate with AI systems like ChatGPT, Claude, or custom AI agents. Our hands-on bootcamp covers prompt structure, context optimization, output refinement, and real-world business applications specific to your industry.',
    'faq.aiconsulting.q2': 'How do you assess AI readiness for SMEs?',
    'faq.aiconsulting.a2': 'Our AI Readiness Audit (from HKD 8,000) analyzes your current workflows, data infrastructure, team capabilities, and business goals. We identify high-ROI AI opportunities, assess technical requirements, and provide a phased implementation roadmap tailored to your budget and resources.',
    'faq.aiconsulting.q3': 'What industries do you provide AI consulting for?',
    'faq.aiconsulting.a3': 'We specialize in AI solutions for service-based SMEs including education centers, event organizers, professional services, training providers, and B2B companies in Hong Kong. Our founder has 14 years of tech experience and has managed systems for 2,000+ participants.',
    'faq.aiconsulting.q4': 'How long does custom AI agent development take?',
    'faq.aiconsulting.a4': 'Custom AI agent projects typically take 4-8 weeks from requirements gathering to deployment. This includes workflow design, integration with your existing systems, testing, and staff training. Pricing starts from HKD 25,000.',
    
    // Answer-first content sections
    'eventxp.what.title': 'What is EventXP Event Check-in System?',
    'eventxp.what.answer': 'EventXP is an event intelligence platform that transforms check-ins into business insights. Beyond attendance tracking, it uses AI to predict which attendees are most likely to buy, renew memberships, or require follow-up—turning event data into actionable sales leads for Hong Kong event organizers.',
    'eventxp.how.title': 'How Does QR Code Check-in Work?',
    'eventxp.how.step1': 'Guests receive a unique QR code via email or WhatsApp',
    'eventxp.how.step2': 'Staff scan the code using EventXP mobile app at the event',
    'eventxp.how.step3': 'System instantly logs attendance and matches guest profile',
    'eventxp.how.step4': 'Automated follow-ups are triggered post-event based on behavior',
    
    'aicrm.what.title': 'What is AI CRM?',
    'aicrm.what.answer': 'AI CRM is customer relationship management software enhanced with artificial intelligence that automatically drafts follow-up messages, predicts lead conversion, and prioritizes prospects. Unlike traditional CRM that only stores data, AI CRM saves SMEs 3+ hours daily on repetitive sales tasks through intelligent automation.',
    'aicrm.benefits.title': 'Top 5 Benefits of AI CRM for Hong Kong SMEs:',
    'aicrm.benefits.1':
      'Our users typically reclaim 3+ hours per week previously spent on manual WhatsApp tracking and copy-pasting replies. (Based on onboarded SME clients, March 2026)',
    'aicrm.benefits.2': 'Smart scheduling eliminates double-booking and keeps your calendar accurate.',
    'aicrm.benefits.3':
      'Draft-first replies in Cantonese or English — you approve before anything is sent.',
    'aicrm.benefits.4':
      'Pipeline visibility so managers see unanswered threads before deals slip.',
    'aicrm.benefits.5': 'WhatsApp integration tailored for Hong Kong business communication',
    'aicrm.pricing.title': 'AI CRM Pricing Comparison Hong Kong',
    'aicrm.pricing.plan': 'Plan',
    'aicrm.pricing.price': 'Price (HKD/month)',
    'aicrm.pricing.bestfor': 'Best For',
    'aicrm.pricing.features': 'Key Features',
    'aicrm.pricing.starter': 'Starter',
    'aicrm.pricing.starter.price': '$2,800',
    'aicrm.pricing.starter.for': 'Small teams',
    'aicrm.pricing.starter.features': 'Basic CRM + AI Email Draft',
    'aicrm.pricing.pro': 'Pro ⭐',
    'aicrm.pricing.pro.price': '$4,800',
    'aicrm.pricing.pro.for': 'Growing businesses',
    'aicrm.pricing.pro.features': 'Full AI + WhatsApp + Forecasting',
    'aicrm.pricing.setup': 'Setup Fee',
    'aicrm.pricing.setup.price': '$15,000+',
    'aicrm.pricing.setup.for': 'One-time',
    'aicrm.pricing.setup.features': 'Data migration + Training',
    
    'aiconsulting.what.title': 'What AI Consulting Services Do We Offer?',
    'aiconsulting.what.answer': 'InnovateXP provides three core AI consulting services for Hong Kong SMEs: AI Readiness Audits (from HKD 8,000) to assess your implementation opportunities, Custom Agent Build (from HKD 25,000) for tailored AI solutions, and Prompt Engineering Training (from HKD 12,000) for hands-on team skill development.',
    'aiconsulting.who.title': 'Who Needs AI Implementation Consulting?',
    'aiconsulting.who.intro': 'AI consulting is ideal for Hong Kong SMEs who:',
    'aiconsulting.who.1': 'You\'ve tried ChatGPT but it\'s not connected to anything in your business',
    'aiconsulting.who.2':
      'You want to automate follow-ups, reporting, or scheduling — but don\'t know which tool fits your stack',
    'aiconsulting.who.3':
      'You\'ve been quoted $200,000 for an AI project and want a reality check',
    'aiconsulting.who.4': 'You need someone who will actually build it, not just slide-deck it',
    'aiconsulting.who.5':
      'Built by a practitioner, not a consultant. Larry Lo has 14 years of hands-on system architecture experience, including high-availability projects for government and public transport in Hong Kong. He is the person who builds and supports your system — not a project manager who subcontracts. Former Google Developer Group HK Organizer · HKSTP Incubation Alumni · Systems handling 2,000+ concurrent active users',

    // Main section direct answers + GEO content gap sections
    'eventxp.main.answer':
      'EventXP turns every check-in into a ranked lead list — automatically. Know who to follow up with, and when, before your competitors do.',
    'eventxp.grid.ai_insight.title': 'Scored follow-up lists',
    'eventxp.grid.ai_insight.body':
      'Stop guessing who was genuinely interested. EventXP scores every attendee based on check-in timing, session attendance, and engagement patterns — so your team follows up with the right 20 people, not all 200.',
    'smartsales.main.answer':
      'SmartSales CRM watches your WhatsApp inbox, ranks every lead by urgency, and drafts a reply in Cantonese or English. You review, tweak 20%, and send. No bot feel. No missed deals.',
    'crm.main.title': 'Why SmartSales? Forged for Hong Kong business culture',
    'crm.main.subtitle': 'Stop losing leads to robotic auto-senders. We believe in "AI Drafts, Human Approves."',
    'crm.usp.1.title': 'Draft-First AI, Not Bots',
    'crm.usp.1.desc': 'Retain human warmth. AI prepares a draft based on context. You confirm. Fast, yet personal.',
    'crm.usp.2.title': 'Native HK Context',
    'crm.usp.2.desc': 'Our AI is tailored for HK "Chinglish" and local business etiquette, unlike foreign bulk-send tools.',
    'crm.usp.3.title': 'Conversation Triage',
    'crm.usp.3.desc': 'Inbound triage: AI highlights which lead is the most urgent and valuable to reply to first.',
    'crm.usp.4.title': 'Manager SLA Dashboard',
    'crm.usp.4.desc': 'Top-down view of unanswered queries. Ensure zero missed opportunities or ignored leads.',
    'crm.usp.5.title': '100% Local HK Team',
    'crm.usp.5.desc': 'Local founder, local use-cases (e.g., BNI, exhibitions). Zero communication barriers for tech support.',
    'addon.title': 'Enterprise Custom Modules',
    'addon.subtitle': 'Bespoke architecture and logic engines for complex business needs.',
    'addon.luma.title': 'Luma & Platform Integration',
    'addon.luma.desc': 'Seamless bi-directional data flow and synchronization between Luma, EventXP, and your existing tools.',
    'addon.commission.title': 'Commission Logic Engine',
    'addon.commission.desc': 'Multi-stage Excel parsing and automated calculation engines with real-time agent dashboards.',
    'addon.ai_predict.title': 'AI Persona & Sales Prediction',
    'addon.ai_predict.desc': 'Deep data insights combining product analysis, buyer persona profiling, and AI forecasting.',
    'addon.architecture.title': 'Enterprise Cloud Architecture',
    'addon.architecture.desc': 'Robust database schema design, QA testing, and scalable cloud deployment.',
    'referral.title': 'EventXP Automatic Referral Program & Welcome Gift',
    'referral.intro': 'By partnering with InnovateXP, you are automatically enrolled in our growth ecosystem.',
    'referral.feedback_loop.title': 'Feedback Loop',
    'referral.feedback_loop.desc': 'Join our beta group to provide product feedback and shape future AI features.',
    'referral.commission.title': '25% Sales Commission',
    'referral.commission.desc': 'As our Sales Director (Honorary), receive a 25% commission on the total first-year contract value for every successful referral.',
    'referral.welcome_gift.title': 'Welcome Gift: Premium Name Cards',
    'referral.welcome_gift.desc': '200 high-end name cards featuring your custom QR code with Linktree setup (linking to LinkedIn, WhatsApp, Instagram, WeChat, etc., as provided by the client) for seamless networking.',
    'aiconsulting.main.answer': 'Our AI consulting service focuses on implementation, not theory. We help SMEs define a realistic roadmap, connect AI to existing workflows, and train teams to operate new processes confidently. The result is a phased rollout with clearer decisions, controlled risk, and measurable operational improvements over time.',
    'timeline.title': 'Typical AI Implementation Timeline for SMEs',
    'timeline.intro': 'Most SME AI projects run in four phases. Actual duration depends on data quality, integration scope, and decision speed, but this framework helps teams plan resources and expectations without overpromising timelines.',
    'timeline.phase1.title': 'Discovery & Blueprint',
    'timeline.phase1.duration': 'Usually 1-2 weeks',
    'timeline.phase1.desc': 'Map current workflows, define business goals, and prioritize highest-value use cases.',
    'timeline.phase2.title': 'Implementation & Integration',
    'timeline.phase2.duration': 'Usually 2-6 weeks',
    'timeline.phase2.desc': 'Build workflows, connect CRM/WhatsApp/calendar systems, and set up role-based operations.',
    'timeline.phase3.title': 'Testing & Team Training',
    'timeline.phase3.duration': 'Usually 1-2 weeks',
    'timeline.phase3.desc': 'Run pilot scenarios, verify data flows, and train staff on daily usage and exception handling.',
    'timeline.phase4.title': 'Optimization',
    'timeline.phase4.duration': 'Ongoing monthly/quarterly',
    'timeline.phase4.desc': 'Tune prompts, improve automation rules, and add incremental capabilities based on usage feedback.',
    'pricing.models.title': 'Common AI CRM & Automation Pricing Models',
    'pricing.models.intro': 'For SMEs, pricing is usually structured by project stage: discovery, pilot, implementation, and ongoing optimization. Final cost depends on workflow complexity, number of users, and required integrations rather than generic one-size-fits-all packages.',
    'pricing.models.col1': 'Model',
    'pricing.models.col2': 'Typical Range',
    'pricing.models.col3': 'How SMEs Use It',
    'pricing.models.discovery.title': 'Discovery / Readiness Audit',
    'pricing.models.discovery.price': 'From HKD 8,000',
    'pricing.models.discovery.desc': 'Low-risk first step to define scope, priorities, and implementation roadmap.',
    'pricing.models.pilot.title': 'Pilot Project (Fixed Scope)',
    'pricing.models.pilot.price': 'From HKD 25,000',
    'pricing.models.pilot.desc': 'Validate one workflow end-to-end before committing to broader rollout.',
    'pricing.models.impl.title': 'Full Implementation Package',
    'pricing.models.impl.price': 'Indicative: HKD 80,000+',
    'pricing.models.impl.desc': 'Deploy across multiple teams, systems, and operational processes.',
    'pricing.models.retainer.title': 'Optimization Retainer',
    'pricing.models.retainer.price': 'Monthly / Quarterly',
    'pricing.models.retainer.desc': 'Continuous improvement, reporting cadence, and process refinement.',
    'roi.title': 'How SMEs Should Measure ROI (Without Guesswork)',
    'roi.intro': 'SME ROI is usually observed through operational behavior first: less manual coordination, fewer follow-up gaps, and clearer decision visibility. Instead of relying on generic benchmark percentages, track simple before/after process signals that reflect your actual business workflow.',
    'roi.point1.title': 'Time Reallocated to Revenue Work',
    'roi.point1.desc': 'Teams spend less effort on repetitive updates and more on customer conversations, demos, and deal progression.',
    'roi.point2.title': 'Fewer Process Errors and Missed Follow-ups',
    'roi.point2.desc': 'Automation and reminders reduce lost context between staff handoffs and improve consistency.',
    'roi.point3.title': 'Better Visibility for Management Decisions',
    'roi.point3.desc': 'Leaders can see which channels, campaigns, or customer segments need attention earlier.',
    'roi.scenario.title': 'Illustrative Scenarios (Not Guaranteed Outcomes)',
    'roi.scenario.1': 'A small sales team can shift part of admin time into extra calls and demos once updates are automated.',
    'roi.scenario.2': 'An event-driven business can identify higher-intent attendee segments faster for targeted follow-ups.',
    
    'about.author.byline': 'By',
    'about.author.title':
      'Built by a practitioner, not a consultant. Larry Lo has 14 years of hands-on system architecture experience, including high-availability projects for government and public transport in Hong Kong. He is the person who builds and supports your system — not a project manager who subcontracts. Former Google Developer Group HK Organizer · HKSTP Incubation Alumni · Systems handling 2,000+ concurrent active users',
    'about.author.updated': 'Last Updated:',
    'about.credentials.title': 'Credentials & Affiliations',
    'about.credentials.experience': 'Tech Experience',
    'about.credentials.participants': 'Event Participants',
  },
  zh: {
    // Header
    'header.title': 'InnovateXP Limited',
    'header.subtitle': '客戶管理系統、企業AI培訓、專業IT諮詢服務',
    'quick.product': '快速閱覽產品/服務',
    
    // Hero Section
    'hero.title': '與你伴行的最強AI建築師',
    'hero.tagline': '攞抱 AI 新藍圖，成就營商新高度',
    'hero.description': '擺脫高競爭與低利潤的困境，利用我們的AI驅動解決方案創造獨特價值。',
    'hero.cta': '聯絡我們',
    'hero.book_meeting': '預約業務交流',
    'hero.tagline_en': 'AI CRM & event systems built in Hong Kong, for SMEs across Asia.',
    'hero.image_alt': 'Larry Lo 演講 — InnovateXP 創辦人，專注香港中小企 AI 與 CRM',
    'hero.explore_services': '了解服務',
    'why.title': '為何選擇 InnovateXP',
    'why.1.label': '14+ 年科技經驗',
    'why.1.sub': '實戰系統與顧問，不只紙上方案。',
    'why.2.label': '2000+ 活動參與者',
    'why.2.sub': '活動與 CRM 系統真實規模驗證。',
    'why.3.label': 'HKSTP 孵化校友',
    'why.3.sub': '扎根香港創科生態。',
    'why.4.label': '本地 AI + CRM 團隊',
    'why.4.sub': '粵語／英文支援區內中小企。',
    'product.entry.eventxp.title': 'EventXP',
    'product.entry.eventxp.blurb': 'QR 簽到、出席分析與活動後跟進。',
    'product.entry.eventxp.cta': '查看 EventXP',
    'product.entry.smartsales.title': 'SmartSales CRM',
    'product.entry.smartsales.blurb': 'AI 輔助銷售漏斗、草擬回覆與排程。',
    'product.entry.smartsales.cta': '查看 SmartSales CRM',
    'product.entry.ai.title': 'AI 顧問',
    'product.entry.ai.blurb': '導入評估、客製 Agent 與團隊 Prompt 培訓。',
    'product.entry.ai.cta': '查看 AI 顧問',
    'product.entry.section_label': '你想優先解決哪個問題？',
    'eventxp.headline': '你花了 HKD 50,000 辦活動，之後那 200 個聯絡人發生了什麼？',
    'smartsales.headline': '你最強的業務 2 小時內就跟進。你的團隊做到嗎？',
    'mockup.checkin': 'EventXP 簽到與儀表板（示意）',
    'mockup.checkin.alt': 'EventXP 後台 — 簽到與儀表板畫面',
    'mockup.pipeline': 'SmartSales 漏斗與 AI 草稿（示意）',
    'mockup.ai': 'AI 草擬與流程（示意）',
    'contact.form.hint.name': '方便我們稱呼您或貴團隊。',
    'contact.form.hint.email': '我們會於 1–2 個工作天內回覆。',
    'contact.form.hint.message': '請簡述你現時最大的 AI／CRM／活動相關挑戰。',
    'footer.book_cta': '預約業務交流',
    'mobile.cta_contact': '聯絡',
    'roi.show_more': '展開更多 ROI 情境說明',
    'roi.show_less': '收合',
    'aiconsulting.who.more': '查看適合客群（展開）',
    
    // Bookme Page
    'bookme.title': '預約業務拜訪',
    'bookme.subtitle': '一對一業務諮詢 — 可預約時段已扣除 Notion 日曆上所有占用（預約與忙碌時段）',
    'bookme.header.title': 'InnovateXP Limited',
    'bookme.header.subtitle': '預約業務拜訪',
    'bookme.header.back': '← 返回首頁',
    'bookme.success.title': '您的業務拜訪預約已成功！已添加到  InnovateXP Limited 日曆。',
    'bookme.success.subtitle': '您的業務拜訪未能預約成功！盡快聯絡InnovateXP Limited : info@innovatexp.com',
    'bookme.whatsapp.title': '📱 發送 WhatsApp 確認訊息',
    'bookme.whatsapp.message': '您的預約已成功添加到 InnovateXP Limited 日曆！點擊下方按鈕發送確認訊息到 WhatsApp。',
    'bookme.whatsapp.button': '打開 WhatsApp 發送',
    'bookme.whatsapp.later': '稍後',
    'bookme.error.title': '請填寫所有必填欄位並選擇日期和時間。',
    'bookme.error.email': '請輸入有效的電子郵件地址。',
    'bookme.error.slots': '無法獲取可用時段',
    'bookme.error.fetch': '獲取時段失敗',
    'bookme.error.booking': '預約失敗，請稍後再試。',
    'bookme.error.general': '預約失敗',
    'bookme.info.title': '📋 預約須知',
    'bookme.info.monday_friday': '• 預約時間為週一至週五，上午 9:00 至下午 5:00',
    'bookme.info.one_hour': '• 每個時段為 1 小時的一對一諮詢',
    'bookme.info.confirmation': '• 預約成功後，您將收到確認郵件及日曆邀請',
    'bookme.info.cancel': '• 如需取消或更改預約，請提前 24 小時通知',
    'bookme.info.online': '• 諮詢可選擇線上會議或實體拜訪',
    'bookme.info.notion': '• 時段與 Notion 同步：當日有任何帶日期的活動都會佔用該時段（例如 14:00–17:00 請設開始與結束時間；可另設 NOTION_BUSY_DB_ID 連結第二個日曆資料庫）',
    'bookme.date.label': '📅 選擇日期',
    'bookme.date.required': '* 週六、週日不開放預約',
    'bookme.time.label': '⏰ 選擇時間 (1小時)',
    'bookme.time.select': '請先選擇日期',
    'bookme.time.loading': '載入中...',
    'bookme.time.no_slots': '此日期沒有可用的時間段。請選擇其他日期。',
    'bookme.time.hour': '* 每個時段為 1 小時的一對一諮詢',
    'bookme.selected.title': '已選擇：',
    'bookme.visitor.title': '👤 訪客資訊',
    'bookme.visitor.name': '您的姓名',
    'bookme.visitor.email': '電子郵件',
    'bookme.visitor.phone': '聯絡電話',
    'bookme.visitor.company': '公司名稱',
    'bookme.visitor.message': '諮詢內容 / 留言',
    'bookme.visitor.placeholder.name': '請輸入您的姓名',
    'bookme.visitor.placeholder.email': 'your@email.com',
    'bookme.visitor.placeholder.phone': '+852 1234 5678',
    'bookme.visitor.placeholder.company': '您的公司名稱',
    'bookme.visitor.placeholder.message': '請簡述您想諮詢的內容，例如：AI 整合方案、系統開發需求、企業培訓等...',
    'bookme.submit.processing': '處理中...',
    'bookme.submit.confirm': '確認預約',
    'bookme.modal.success.title': '預約成功',
    'bookme.modal.error.title': '預約失敗',

    // Vision Section
    'vision.title': '我們的願景',
    'vision.brand': 'InnovateXP Limited',
    'vision.tagline': 'Innovate • Transform • Experience',
    'vision.description': '在 InnovateXP，我們相信每一家企業都值得擁有 AI 和數據驅動的洞察力。我們不僅僅是開發軟件—我們是您競爭優勢的建築師。從活動管理到客戶關係，我們將複雜的挑戰轉化為優雅的解決方案，推動可衡量的增長。',
    'vision.innovate': '創新 Innovate',
    'vision.innovate_desc': '以 AI 驅動的解決方案挑戰現狀，將數據轉化為您的戰略資產。',
    'vision.transform': '轉型 Transform',
    'vision.transform_desc': '將您的業務運營從手動流程演變為智能自動化。',
    'vision.experience': '體驗 Experience',
    'vision.experience_desc': '提供超越預期的卓越成果，創造持久影響。',

    // Core Services Section (Three Main Services)
    'services.title': '我們的核心服務',
    'services.ai_crm.title': 'SmartSales CRM',
    'services.ai_crm.subtitle': '智能客戶管理系統',
    'services.ai_crm.benefit1': 'AI智能草稿提供專業快速回覆',
    'services.ai_crm.benefit2': '自動化預訂處理',
    'services.ai_crm.benefit3': '自動標記和跟進提醒消除遺漏訂單',
    'services.ai_crm.cta': '了解AI CRM解決方案',
    'services.checkin.title': 'EventXP 實時簽到系統',
    'services.checkin.subtitle': '簽到系統',
    'services.checkin.benefit1': '實時參與者列表',
    'services.checkin.benefit2': 'QR碼掃描',
    'services.checkin.benefit3': '自動統計',
    'services.checkin.cta': '了解簽到系統',
    'services.courses.title': 'AI 顧問服務',
    'services.courses.subtitle': '協助企業從 0 到 1 導入 AI',
    'services.courses.benefit1': '導入評估：大幅減少試錯成本',
    'services.courses.benefit2': '客製化 AI Agent 與架構設計',
    'services.courses.benefit3': '實戰 Prompt Engineering 培訓',
    'services.courses.cta': '了解顧問服務',
    
    // About Section
    'about.title': '關於我們',
    'about.intro.title': '關於 InnovateXP Limited',
    'about.intro.p1': '由 Larry Lo 創立（前 GDG HK Organiser，任期至 2025 年；2017-2019 HKSTP Incubatee）。我們不僅是你的IT顧問，更是實戰派的系統架構師。',
    'about.intro.p2': '我們的理念：「以熱誠、完美與卓越連結科技」。憑藉多年的系統設計 (System Design) 與實戰開發經驗，我們助您建立專屬的「沙漠綠洲」。',
    'about.intro.p3': '我們將創業公司的敏捷開發思維與企業級的穩定性完美結合，提供真正「可落地、可實施」的 AI 解決方案。',
    
    'about.tags.title': '我們的戰略與實力',
    'about.tags.red_ocean.title': '紅海困境',
    'about.tags.red_ocean.description': '高競爭、低利潤、同質化。若只做別人都在做的事，價值將被無限攤薄。你需要技術壁壘來突圍。',
    'about.tags.desert_oasis.title': '沙漠綠洲戰略',
    'about.tags.desert_oasis.description': '利用 AI 建立數據護城河。創造競爭對手無法輕易複製的獨特價值，建立屬於您的藍海綠洲。',
    'about.tags.community.title': '實戰驗證的技術力',
    'about.tags.community.description': '創始人擁有處理 2000+ 參與者規模的活動系統設計經驗。我們深知如何構建高併發、高穩定的系統，拒絕紙上談兵。',
    
    'about.story.title': '使命與 2026 路線圖',
    'about.story.content': 'InnovateXP 賦能企業，通過 AI 與系統藍圖實現業務升級。2026 部署：1月 (現在) - EventXP 發布；2月 - SmartSales CRM；3月 - AI 實戰手冊；4月 - 中小企 AI 課程。我們致力於技術落地。',

    // Partnership Section
    'partnership.title': '可信賴的合作夥伴與聯盟',
    'partnership.subtitle': '透過策略合作夥伴關係建立創新',
    'partnership.agilizing.title': '善敏教育中心',
    'partnership.agilizing.desc': '敏捷與企業培訓夥伴',
    'partnership.bni_anchor.title': 'BNI Anchor',
    'partnership.bni_anchor.desc': '引薦網絡與領導力',
    'partnership.linkedinlocal.title': 'LinkedInLocal Asia',
    'partnership.linkedinlocal.desc': '亞太專業社群聚會',
    'partnership.ex_io.title': 'EX.IO',
    'partnership.ex_io.desc': '數字資產與交易生態夥伴',
    'partnership.kirapay.title': 'KiraPay',
    'partnership.kirapay.desc': '支付與金融科技協作',
    
    // Contact Section
    'contact.title': '聯絡我們',
    'contact.subtitle': '請留下訊息，我們會盡快回覆您。',
    'contact.form.name': '姓名',
    'contact.form.email': '電郵地址',
    'contact.form.content': '內容',
    'contact.form.placeholder': '請填寫',
    'contact.form.submit': '發送電郵',
    'contact.form.success': '電郵已發送',
    
    // Story Section (3-Step)
    'story.title': '我們的策略',
    'story.step1.title': '紅海困境',
    'story.step1.description': '高競爭、低利潤、人人做同樣的事',
    'story.step2.title': '沙漠綠洲',
    'story.step2.description': '利用AI創造獨特價值，逃離競爭',
    'story.step3.title': '可樂理論',
    'story.step3.description': '相同產品，在不同環境中呈現不同價值',
    
    // Ideal Client Section
    'ideal.title': '理想引薦 / 理想客戶輪廓',
    'ideal.subtitle': '我們為中小企業解決的問題',
    'ideal.problem1': '太多WhatsApp查詢',
    'ideal.problem2': '漏單',
    'ideal.problem3': 'Excel混亂',
    'ideal.problem4': '缺乏CRM自動化',
    'ideal.value': '為中小企業明確的價值主張',
    
    // Founder Section
    'founder.title': '創辦人與資歷',
    'founder.name': 'Larry Lo',
    'founder.credential1': 'SAFe認證',
    'founder.credential2': 'Google Developer Group 講者',
    'founder.credential3': '200+開發者培訓經驗',
    'founder.credential4': 'HKSTP孵化',
    'founder.credential5': 'JCI/BNI領導',
    
    // Achievements Section
    'achievements.title': '實績與影響',
    'achievements.kmb': 'KMB / 政府專案',
    'achievements.government': '高風險環境系統',
    'achievements.sme': '中小企業專案',
    'achievements.engagement': '提升用戶參與度達100%',
    'achievements.case': 'AI × CRM成功案例',
    
    // Credibility Badges
    'credibility.title': '合作夥伴與認可',
    'credibility.gdg': 'GDG Hong Kong',
    'credibility.hku': 'HKU',
    'credibility.hkstp': 'HKSTP',
    'credibility.jci': 'JCI',
    'credibility.bni': 'BNI',
    
    // Product Showcases
    'showcase.title': '',
    'showcase.problem_label': '遇到的問題：',
    'showcase.solution_label': '我們的解決方案：',
    'showcase.features_label': '核心功能：',
    'showcase.screenshot_coming': '📬 預約 15 分鐘現場示範 — info@innovatexp.com',
    'showcase.checkin.title': 'EventXP',
    'showcase.checkin.subtitle': 'QR Code + 即時同步',
    'showcase.checkin.problem': '手動簽到容易出錯、遺漏數據，會後統計費時費力',
    'showcase.checkin.solution': 'QR Code 掃描簽到，即時同步到 Notion 資料庫，會長隨時查閱出席率與統計報表',
    'showcase.checkin.features': 'QR Code 快速簽到; 自動統計報表; 實時參加者名單; 支援多場次活動',
    'showcase.checkin.cta': '預約了解簽到系統',
    'showcase.booking.title': '預約 / 預訂系統',
    'showcase.booking.subtitle': 'Notion Calendar + Email + WhatsApp 通知',
    'showcase.booking.problem': 'WhatsApp 反覆確認時間，日曆散亂，容易撞期或遺漏',
    'showcase.booking.solution': '客戶自選時段，系統自動檢查空檔，確認後即刻加入 Notion Calendar，並發送 .ics 行事曆附件與 WhatsApp 確認',
    'showcase.booking.features': '可視化日曆選擇; 即時空檔檢查; Notion Calendar 同步; Email 自動寄送 .ics 附件',
    'showcase.booking.cta': '預約了解預訂系統',
    'showcase.ai_crm.title': 'AI × CRM',
    'showcase.ai_crm.subtitle': '智能客戶關係管理系統',
    'showcase.ai_crm.problem': 'WhatsApp 訊息散落，靠人工記錄容易錯漏，無法系統化追蹤客戶狀態與銷售進度',
    'showcase.ai_crm.solution': '整合 AI 自動標記、草擬回覆、提醒跟進，將客戶資訊集中管理，銷售漏斗一目了然',
    'showcase.ai_crm.feature1': 'AI 智能草稿 - 快速生成專業回覆',
    'showcase.ai_crm.feature2': '自動標記 - 客戶狀態自動分類',
    'showcase.ai_crm.feature3': '跟進提醒 - 消除遺漏訂單',
    'showcase.ai_crm.feature4': '銷售漏斗 - 可視化管理客戶旅程',
    'showcase.ai_crm.cta': '預約了解AI CRM',
    'ideal.cta': '立即預約諮詢',
    
    // Pricing Section
    'pricing.title': '產品定價方案',
    'pricing.subtitle': '數據變現 + 社群留存 = 長遠增長',
    'pricing.promotion': 'Q1 推出優惠',
    'pricing.promotion_detail': '簽約一年，免費贈送 1 場 Man-day 客製化諮詢',
    
    // EventXP Product
    'pricing.insight.name': 'EventXP',
    'pricing.insight.tagline': '將活動數據轉化為營收增長',
    'pricing.insight.subtitle': '智能活動數據系統',
    'pricing.insight.description': '別讓您的訪客數據在 Excel 裡沉睡。將出席記錄升級為深度客戶洞察，創造可持續的業績增長。',
    'pricing.insight.value': '預測參加者興趣，留住社群成員，精準鎖定明年買家。',
    
    'pricing.insight.tier1.name': 'Starter',
    'pricing.insight.tier1.price': 'HKD $1,480',
    'pricing.insight.tier1.period': '/ 月',
    'pricing.insight.tier1.target': '1 個社群 · 最少 6 個月',
    'pricing.insight.tier1.feature1': '無限活動建立及 QR Code 簽到',
    'pricing.insight.tier1.feature2': '精準轉化名單及留存策略引擎',
    'pricing.insight.tier1.feature3': '營運支援及備份 · 含 2 次現場活動支援',
    'pricing.insight.tier1.feature4': '3 個月保養 · 1 次產品檢討會議',
    
    'pricing.insight.tier2.name': 'Growth',
    'pricing.insight.tier2.price': 'HKD $1,980',
    'pricing.insight.tier2.period': '/ 月',
    'pricing.insight.tier2.subtitle': '(僅比 Starter 多 $500)',
    'pricing.insight.tier2.badge': '超值推薦',
    'pricing.insight.tier2.target': '2 個社群 · 最少 12 個月',
    'pricing.insight.tier2.feature1': '包含 Starter 所有功能，另加：',
    'pricing.insight.tier2.feature2': '🕵️ AI 潛在興趣透視（簽到行為 → 推斷興趣）',
    'pricing.insight.tier2.feature3': '3 次現場支援 · 每年 2 次策略 AI 諮詢',
    'pricing.insight.tier2.feature4': '1 年保養 · 2 次產品檢討會議',
    'pricing.insight.tier2.note': '💡 適合重視社群留存與數據跟進。預付 1 年享 10% 折扣；2 年享 20% 折扣。',
    
    'pricing.insight.tier3.name': 'Enterprise',
    'pricing.insight.tier3.price': 'HKD $2,480',
    'pricing.insight.tier3.period': '/ 月',
    'pricing.insight.tier3.target': '4 個社群 · 最少 12 個月',
    'pricing.insight.tier3.feature1': '包含 Growth 所有功能，另加每月 1 次 AI 諮詢（60 分鐘）',
    'pricing.insight.tier3.feature2': '4 次現場支援 · 2 年保養 · 3 次產品檢討會議',
    'pricing.insight.tier3.feature3': '持續優化、流程自動化及策略支援',
    
    'pricing.insight.setup': '若經查出預約者為 BNI 成員，場景和價格可議。詳情請',
    'pricing.insight.setup_cta': '預約洽談',
    'eventxp.communities_support':
      '各方案支援社群活動：Starter 1 個社群、Growth 2 個、Enterprise 4 個；並可享用試用活動 1 次。',
    'mockup.pipeline_kanban': 'SmartSales — 管道／看板（畫面示意）',
    'mockup.pipeline_inbox': 'SmartSales — 收件匣與管道（畫面示意）',
    
    // SmartSales CRM Product
    'pricing.crm.name': 'SmartSales CRM',
    'pricing.crm.tagline': '用 AI 複製您的金牌業務員',
    'pricing.crm.subtitle': 'AI 銷售增長引擎',
    'pricing.crm.description': '讓 AI 成為你的頂級銷售助理。從寫信、排程到分析，自動化繁瑣工作，讓你專注於成交。',
    'pricing.crm.value': '自動化跟進、預約與分析，節省 70% 行政時間。',
    
    'pricing.crm.feature1.title': 'AI 智能寫作與回覆',
    'pricing.crm.feature1.desc': '情境感知回覆：當客戶說「太貴了」，AI 自動草擬一封強調「價值與 ROI」的回信供 Sales 修改。',
    'pricing.crm.feature2.title': '智能排程',
    'pricing.crm.feature2.desc': '自動預約：整合 Google/Outlook Calendar，AI 機器人可以直接在對話中與客戶確認空檔，並發送會議邀請。',
    'pricing.crm.feature3.title': '洞察報告',
    'pricing.crm.feature3.desc': '銷售預測：AI 分析目前的 Pipeline，預測本月營收達標率。',
    
    'pricing.crm.tier1.name': 'Starter',
    'pricing.crm.tier1.price': 'HKD $2,800',
    'pricing.crm.tier1.period': '/ 月',
    'pricing.crm.tier1.target': '輕量版',
    'pricing.crm.tier1.feature1': '基礎 CRM 功能（客戶資料庫）',
    'pricing.crm.tier1.feature2': '基礎 AI 寫作（Email Draft）',
    'pricing.crm.tier1.feature3': '標準銷售報表',
    
    'pricing.crm.tier2.name': 'Pro',
    'pricing.crm.tier2.price': 'HKD $4,800',
    'pricing.crm.tier2.period': '/ 月',
    'pricing.crm.tier2.badge': '全功能 AI',
    'pricing.crm.tier2.target': '全功能 AI 版',
    'pricing.crm.tier2.feature1': '進階 AI 功能：自動回覆建議、智能排程、流失預警',
    'pricing.crm.tier2.feature2': 'Insight Report：AI 銷售預測與戰略建議',
    'pricing.crm.tier2.feature3': 'WhatsApp / Email 雙向整合',
    
    'pricing.crm.tier3.name': '導入與設定',
    'pricing.crm.tier3.price': 'HKD $15,000 起',
    'pricing.crm.tier3.period': '(一次性)',
    'pricing.crm.tier3.target': '（導入與設定）',
    'pricing.crm.tier3.feature1': '由現有 Excel／CRM 遷移資料',
    'pricing.crm.tier3.feature2': '按你產品與語氣訓練專屬 AI Prompt',
    'pricing.crm.tier3.feature3': '2 小時團隊上手導覽',
    'pricing.crm.tier3.feature4': '大多數客戶可於 5–7 個工作天上線。如不確定是否需要？先預約免費 30 分鐘聊聊。',
    
    'pricing.cta': '預約諮詢',
    'pricing.contact': '聯絡了解詳情',
    
    // Roadmap Section
    'roadmap.title': '2026路線圖',
    'roadmap.jan': '1月 - 簽到系統發布',
    'roadmap.feb': '2月 - AI客戶管理系統',
    'roadmap.mar': '3月 - AI實用手冊',
    'roadmap.apr': '4月 - 中小企AI實用課程',
    
    // Newsletter Section
    'newsletter.title': '保持聯繫',
    'newsletter.subtitle': '訂閱我們的電子報，獲取最新的 AI 洞察和更新',
    'newsletter.name': '您的姓名',
    'newsletter.email': '您的電郵',
    'newsletter.interests': '興趣',
    'newsletter.interest.ai': 'AI',
    'newsletter.interest.tech': '科技',
    'newsletter.interest.crm': 'CRM',
    'newsletter.interest.events': '活動',
    'newsletter.subscribe': '訂閱',
    'newsletter.success': '訂閱成功！感謝您的加入。',
    'newsletter.error': '訂閱失敗，請重試。',
    
    // AI Consulting Section
    'ai_consulting.title': 'AI 顧問服務',
    'ai_consulting.subtitle': '從策略到落地實施',
    'ai_consulting.description': '我們以實戰為導向的顧問服務，協助企業探索 AI 應用之路。',
    'ai_consulting.package1.name': 'AI 導入評估',
    'ai_consulting.package1.price': 'HKD $8,000 起',
    'ai_consulting.package1.desc': '全面評估您的組織 AI 準備程度與機會',
    'ai_consulting.package1.feature1': '現狀分析',
    'ai_consulting.package1.feature2': 'AI 機會識別',
    'ai_consulting.package1.feature3': '實施路線圖',
    'ai_consulting.package2.name': '客製化 AI Agent',
    'ai_consulting.package2.price': 'HKD $25,000 起',
    'ai_consulting.package2.desc': '為您的業務需求量身打造的 AI 代理',
    'ai_consulting.package2.feature1': '客製化工作流程設計',
    'ai_consulting.package2.feature2': '與現有系統整合',
    'ai_consulting.package2.feature3': '持續支援與優化',
    'ai_consulting.package3.name': 'Prompt 實戰訓練營',
    'ai_consulting.package3.price': 'HKD $12,000 起',
    'ai_consulting.package3.desc': '實戰培訓，讓您的團隊掌握 AI 提示工程',
    'ai_consulting.package3.feature1': '互動式工作坊',
    'ai_consulting.package3.feature2': '真實案例研究',
    'ai_consulting.package3.feature3': '客製化提示庫',
    
    // Navigation
    'nav.home': '首頁',
    'nav.eventxp': 'EventXP',
    'nav.smartsales': 'SmartSales CRM',
    'nav.ai_consulting': 'AI 顧問',
    'nav.about': '關於我們',
    'nav.contact': '聯絡我們',
    'nav.vision': '願景',
    'nav.partnership': '合作夥伴',
    
    // Footer
    'footer.copyright': `© ${new Date().getFullYear()} InnovateXP Limited. 版權所有。`,
    
    // FAQ Sections
    'faq.smartsales.title': 'SmartSales CRM - 常見問題',
    'faq.smartsales.q1': '什麼是 AI CRM？它與傳統 CRM 有何不同？',
    'faq.smartsales.a1': 'AI CRM 是結合人工智能的客戶關係管理軟件。與僅儲存數據的傳統 CRM 不同，AI CRM 能自動草擬跟進訊息、預測哪些潛在客戶會轉化，並根據行為模式優先處理潛在客戶。它能為中小企業每天節省 3 小時以上的重複性銷售工作。',
    'faq.smartsales.q2': 'AI CRM 能否與 WhatsApp 整合以服務香港企業？',
    'faq.smartsales.a2': '可以。SmartSales CRM 直接與 WhatsApp Business API 整合，讓香港企業接收查詢、自動草擬中文或英文回覆，並追蹤對話歷史——全部在一個平台上完成。發送前需要人工審批。',
    'faq.smartsales.q3': '在香港使用 AI CRM 需要多少費用？',
    'faq.smartsales.a3': 'SmartSales CRM Starter 計劃月費由 HKD 2,800 起，Pro 全功能 AI 計劃月費 HKD 4,800。企業定價取決於用戶數量和整合需求。請聯絡我們獲取定制報價。',
    'faq.smartsales.q4': '實施 AI CRM 需要多長時間？',
    'faq.smartsales.a4': '基本設置需要 1-2 週，包括數據遷移和團隊培訓。完整的 WhatsApp 整合和定制工作流程通常需要 3-4 週。我們全程提供實戰導入支援。',
    'faq.smartsales.q5': 'AI 驅動的客戶管理能帶來什麼投資回報？',
    'faq.smartsales.a5': '客戶通常在第一個月內看到：遺漏跟進減少 70%、每天節省 3+ 小時手動工作、潛在客戶回應時間改善 40%。',
    
    'faq.eventxp.title': 'EventXP - 常見問題',
    'faq.eventxp.q1': '什麼是 EventXP 活動簽到系統？',
    'faq.eventxp.a1': 'EventXP 是一個活動情報平台，將簽到轉化為商業洞察。除了出席追蹤，它還能預測哪些參加者最有可能購買、續會或需要跟進——將活動數據轉化為可操作的銷售線索。',
    'faq.eventxp.q2': 'QR 碼簽到如何運作？',
    'faq.eventxp.a2': '賓客通過電郵或 WhatsApp 收到獨特的 QR 碼。在活動現場，工作人員使用 EventXP 手機應用掃描 QR 碼。系統即時記錄出席、將賓客資料與您的 CRM 配對，並可在活動後觸發自動跟進。',
    'faq.eventxp.q3': 'EventXP 能否處理多個同時進行的活動？',
    'faq.eventxp.a3': '可以。EventXP 支援無限數量的同步活動，配備獨立儀表板、即時出席追蹤，並可整合所有活動的報告。',
    'faq.eventxp.q4': 'EventXP 活動管理系統的費用是多少？',
    'faq.eventxp.a4': 'EventXP Starter 月費 HKD 1,480（1 個社群、2 次現場支援）。Growth 月費 HKD 1,980，含 AI 潛在興趣透視及每年 2 次 AI 諮詢。Enterprise 月費 HKD 2,480，含每月 AI 諮詢及 4 次現場支援。一次性設定：BNI 成員可議價，詳情請預約洽談。',
    
    'faq.aiconsulting.title': 'AI 顧問服務 - 常見問題',
    'faq.aiconsulting.q1': '什麼是 Prompt Engineering 培訓？',
    'faq.aiconsulting.a1': 'Prompt Engineering 培訓教導您的團隊如何有效地與 AI 系統（如 ChatGPT、Claude 或定制 AI 代理）溝通。我們的實戰訓練營涵蓋提示結構、上下文優化、輸出精煉，以及針對您行業的真實商業應用。',
    'faq.aiconsulting.q2': '你們如何評估中小企業的 AI 準備度？',
    'faq.aiconsulting.a2': '我們的 AI 準備度評估（HKD 8,000 起）分析您目前的工作流程、數據基礎設施、團隊能力和業務目標。我們識別高回報的 AI 機會、評估技術需求，並提供針對您預算和資源的分階段實施路線圖。',
    'faq.aiconsulting.q3': '你們為哪些行業提供 AI 顧問服務？',
    'faq.aiconsulting.a3': '我們專注為服務型中小企業提供 AI 解決方案，包括教育中心、活動組織者、專業服務、培訓機構和香港的 B2B 公司。我們的創辦人擁有 14 年科技經驗，曾管理 2,000+ 參與者規模的系統。',
    'faq.aiconsulting.q4': '定制 AI 代理開發需要多長時間？',
    'faq.aiconsulting.a4': '定制 AI 代理項目從需求收集到部署通常需要 4-8 週。這包括工作流程設計、與現有系統整合、測試和員工培訓。定價由 HKD 25,000 起。',
    
    // Answer-first content sections
    'eventxp.what.title': '什麼是 EventXP 活動簽到系統？',
    'eventxp.what.answer': 'EventXP 是一個活動情報平台，將簽到轉化為商業洞察。除了出席追蹤，它使用 AI 預測哪些參加者最有可能購買、續會或需要跟進——將活動數據轉化為可操作的銷售線索，專為香港活動組織者設計。',
    'eventxp.how.title': 'QR 碼簽到如何運作？',
    'eventxp.how.step1': '賓客通過電郵或 WhatsApp 收到獨特的 QR 碼',
    'eventxp.how.step2': '工作人員在活動現場使用 EventXP 手機應用掃描 QR 碼',
    'eventxp.how.step3': '系統即時記錄出席並配對賓客資料',
    'eventxp.how.step4': '活動後根據行為自動觸發跟進',
    
    'aicrm.what.title': '什麼是 AI CRM？',
    'aicrm.what.answer': 'AI CRM 是結合人工智能的客戶關係管理軟件，能自動草擬跟進訊息、預測潛在客戶轉化，並優先處理潛在客戶。與僅儲存數據的傳統 CRM 不同，AI CRM 透過智能自動化，為中小企業每天節省 3 小時以上的重複性銷售工作。',
    'aicrm.benefits.title': '香港中小企業使用 AI CRM 的 5 大好處：',
    'aicrm.benefits.1': '自動化跟進減少 70% 遺漏機會',
    'aicrm.benefits.2': '智能排程消除重複預約，每天節省 3+ 小時',
    'aicrm.benefits.3': 'AI 驅動回覆提升 40% 潛在客戶回應時間',
    'aicrm.benefits.4': '85% 準確度的銷售預測，助您更好規劃',
    'aicrm.benefits.5': '專為香港商業通訊定制的 WhatsApp 整合',
    'aicrm.pricing.title': '香港 AI CRM 定價比較',
    'aicrm.pricing.plan': '計劃',
    'aicrm.pricing.price': '價格 (HKD/月)',
    'aicrm.pricing.bestfor': '最適合',
    'aicrm.pricing.features': '主要功能',
    'aicrm.pricing.starter': 'Starter',
    'aicrm.pricing.starter.price': '$2,800',
    'aicrm.pricing.starter.for': '小型團隊',
    'aicrm.pricing.starter.features': '基礎 CRM + AI 電郵草稿',
    'aicrm.pricing.pro': 'Pro ⭐',
    'aicrm.pricing.pro.price': '$4,800',
    'aicrm.pricing.pro.for': '成長型企業',
    'aicrm.pricing.pro.features': '全功能 AI + WhatsApp + 預測',
    'aicrm.pricing.setup': 'Setup 費用',
    'aicrm.pricing.setup.price': '$15,000+',
    'aicrm.pricing.setup.for': '一次性',
    'aicrm.pricing.setup.features': '數據遷移 + 培訓',
    
    'aiconsulting.what.title': '我們提供哪些 AI 顧問服務？',
    'aiconsulting.what.answer': 'InnovateXP 為香港中小企業提供三項核心 AI 顧問服務：AI 準備度評估（HKD 8,000 起）評估您的實施機會、定制 AI 代理構建（HKD 25,000 起）提供量身定制的 AI 解決方案，以及 Prompt Engineering 培訓（HKD 12,000 起）提供實戰團隊技能發展。',
    'aiconsulting.who.title': '誰需要 AI 實施顧問？',
    'aiconsulting.who.intro': 'AI 顧問服務最適合以下香港中小企業：',
    'aiconsulting.who.1': '想採用 AI 但不知從何開始',
    'aiconsulting.who.2': '需要減少 AI 實施的試錯成本',
    'aiconsulting.who.3': '需要針對特定業務工作流程的定制 AI 代理',
    'aiconsulting.who.4': '希望團隊接受實用的 Prompt Engineering 培訓',
    'aiconsulting.who.5': '尋求 14 年科技老兵的專業指導',

    // Main section direct answers + GEO content gap sections
    'eventxp.main.answer': 'EventXP 協助香港及大灣區活動團隊將簽到紀錄轉化為可執行的商業洞察。你可以即時查看出席情況、識別高意向參加者，並安排後續跟進流程，避免活動結束後只剩零散報表與難以行動的資料。',
    'eventxp.grid.ai_insight.title': '自動評分的跟進名單',
    'eventxp.grid.ai_insight.body': '不再靠感覺猜誰最有興趣。EventXP 會根據簽到時間、出席狀況與互動訊號為每位參加者評分，讓你先跟進最值得的 20 人，而不是把 200 人全部都追一次。',
    'smartsales.main.answer': 'SmartSales CRM 為中小企業提供可落地的 AI CRM 流程，把 WhatsApp 對話、潛在客戶進度與跟進提醒整合到同一系統。團隊可減少手動更新與跨工具切換，讓銷售管道更清晰、回應更快、服務更一致。',
    'crm.main.title': '專為香港商業文化鑄造',
    'crm.main.subtitle': '拒絕冷冰冰的機械人。我們的核心哲學是：「AI 幫你諗，你話事。」',
    'crm.usp.1.title': '獨家 AI 草稿模式',
    'crm.usp.1.desc': 'AI 自動閱讀上文下理並準備「回覆草稿」，Sales 看一眼按 Confirm 即可，保留真人溫度。',
    'crm.usp.2.title': '精通廣東話與中英夾雜',
    'crm.usp.2.desc': '精準掌握本地商業語境，讓客戶覺得是在跟本地專業顧問對話，信任度極高。',
    'crm.usp.3.title': '智能分流與優先級排序',
    'crm.usp.3.desc': 'AI 自動分析湧入的訊息，幫你判斷「哪個客最急？」、「哪張單最值錢？」，火力集中高價值客戶。',
    'crm.usp.4.title': '管理層 SLA 儀表板',
    'crm.usp.4.desc': '清晰顯示「過了 48 小時未回覆的查詢」，徹底解決 Sales 漏單痛點，管理層一目了然。',
    'crm.usp.5.title': '100% 本地團隊與支援',
    'crm.usp.5.desc': '深明香港 SME 真實場景（如 BNI 跟進、展覽 Lead），提供最貼地的本地技術支援，溝通零障礙。',
    'addon.title': '企業級客製化擴充模組',
    'addon.subtitle': '專為複雜業務邏輯與高負載需求打造的系統架構。',
    'addon.luma.title': 'Luma 與多平台數據打通',
    'addon.luma.desc': '實現 Luma、EventXP 與現有系統間的雙向數據同步，告別手動匯出 Excel。',
    'addon.commission.title': '自動化佣金計算引擎',
    'addon.commission.desc': '多階段 Excel 解析與自訂分佣邏輯，配備專屬 Dashboard 讓銷售表現一目了然。',
    'addon.ai_predict.title': 'AI 買家畫像與銷售預測',
    'addon.ai_predict.desc': '深度數據分析，結合產品定位、客戶畫像 (Persona) 及 AI 驅動的銷售預測模型。',
    'addon.architecture.title': '企業級雲端架構部署',
    'addon.architecture.desc': '穩健的資料庫 Schema 設計、嚴格 QA 測試與可擴展的雲端環境建置。',
    'referral.title': 'EventXP 自動轉介紹計劃與迎新禮遇',
    'referral.intro': '與 InnovateXP 合作，即自動加入我們的 Growth Ecosystem。',
    'referral.feedback_loop.title': '產品共創 Feedback Loop',
    'referral.feedback_loop.desc': '加入內部 Beta 用戶群，一齊提供產品回饋，優先體驗及影響未來 AI 功能。',
    'referral.commission.title': '25% 轉介紹佣金',
    'referral.commission.desc': '以榮譽 Sales Director 身份，為每一張成功轉介紹的一年合約總額，獲得 25% 佣金回贈。',
    'referral.welcome_gift.title': '迎新禮遇：高級卡片套裝',
    'referral.welcome_gift.desc': '獲贈 200 張高質感 Name Card，印上你的專屬 QR Code 及 Linktree（可連結 LinkedIn、WhatsApp、Instagram、WeChat 等），讓你在人脈場合一掃即加。',
    'aiconsulting.main.answer': '我們的 AI 顧問服務重點是實施而非空泛策略。透過分階段路線圖、系統整合與團隊培訓，中小企業可以在可控風險下逐步導入 AI，並以實際營運改善來衡量成效，而非只看理想化指標。',
    'timeline.title': '中小企業 AI 導入常見時間線',
    'timeline.intro': '大多數中小企業 AI 項目可分為四個階段。實際時間取決於資料品質、整合範圍與決策速度，但以下框架可協助你更實際地規劃資源與進度。',
    'timeline.phase1.title': '需求盤點與藍圖',
    'timeline.phase1.duration': '通常 1-2 週',
    'timeline.phase1.desc': '盤點現有流程，定義業務目標，並優先排序高價值導入場景。',
    'timeline.phase2.title': '實作與系統整合',
    'timeline.phase2.duration': '通常 2-6 週',
    'timeline.phase2.desc': '建立流程、串接 CRM/WhatsApp/日曆等系統，並配置角色權限。',
    'timeline.phase3.title': '測試與團隊培訓',
    'timeline.phase3.duration': '通常 1-2 週',
    'timeline.phase3.desc': '以試行場景驗證資料流，並訓練團隊日常操作與例外處理。',
    'timeline.phase4.title': '持續優化',
    'timeline.phase4.duration': '按月／按季持續',
    'timeline.phase4.desc': '根據使用反饋調整提示詞、自動化規則與後續功能擴展。',
    'pricing.models.title': 'AI CRM 與自動化常見定價模式',
    'pricing.models.intro': '中小企業常見收費通常按項目階段劃分：盤點、試點、正式導入與持續優化。最終費用主要受流程複雜度、用戶數與整合需求影響，而非單一固定方案。',
    'pricing.models.col1': '模式',
    'pricing.models.col2': '常見範圍',
    'pricing.models.col3': '中小企業使用情境',
    'pricing.models.discovery.title': '盤點／準備度評估',
    'pricing.models.discovery.price': 'HKD 8,000 起',
    'pricing.models.discovery.desc': '以較低風險先釐清範圍、優先次序與導入路線圖。',
    'pricing.models.pilot.title': '試點項目（固定範圍）',
    'pricing.models.pilot.price': 'HKD 25,000 起',
    'pricing.models.pilot.desc': '先驗證一條流程端到端價值，再決定是否全面擴展。',
    'pricing.models.impl.title': '完整導入方案',
    'pricing.models.impl.price': '參考：HKD 80,000+',
    'pricing.models.impl.desc': '跨部門、跨系統的完整部署與營運流程落地。',
    'pricing.models.retainer.title': '持續優化顧問',
    'pricing.models.retainer.price': '按月／按季',
    'pricing.models.retainer.desc': '持續調整、定期檢視成效與流程優化。',
    'roi.title': '中小企業如何衡量 ROI（避免空泛估算）',
    'roi.intro': 'ROI 通常先反映在營運行為：人工協調減少、跟進遺漏下降、管理可視性提升。與其套用外部百分比，不如追蹤自身流程前後差異，得到更可信且可行動的判斷。',
    'roi.point1.title': '把時間轉回高價值工作',
    'roi.point1.desc': '團隊可把重複更新時間轉移到客戶溝通、示範與成交推進。',
    'roi.point2.title': '減少流程錯漏與遺漏跟進',
    'roi.point2.desc': '自動提醒和標準化流程可降低交接斷點與跟進遺漏。',
    'roi.point3.title': '提升管理層決策可見度',
    'roi.point3.desc': '管理者可更早看見哪些渠道、活動或客群需要調整。',
    'roi.scenario.title': '示意情境（非保證結果）',
    'roi.scenario.1': '小型銷售團隊在自動化更新後，可把部分行政時間轉為額外通話與示範。',
    'roi.scenario.2': '活動型業務可更快辨識高意向參加者分群，集中資源做精準跟進。',
    
    'about.author.byline': '作者：',
    'about.author.title': 'InnovateXP 創辦人 | 14 年科技老兵 | AI 顧問 | 前 GDG Hong Kong Organizer',
    'about.author.updated': '最後更新：',
    'about.credentials.title': '資歷與聯盟',
    'about.credentials.experience': '科技經驗',
    'about.credentials.participants': '活動參與者',
  },
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    // Load language from localStorage on mount
    if (typeof window !== 'undefined') {
      const savedLanguage = localStorage.getItem('language') as Language;
      if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'zh')) {
        setLanguageState(savedLanguage);
      }
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    if (typeof window !== 'undefined') {
      localStorage.setItem('language', lang);
    }
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
